default: &default
  adapter: postgresql
  encoding: unicode 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: intranet_sinoredi_development
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: intranet_sinoredi_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  database: intranet_sinoredi_production
  username: intranet_sinoredi
  password: <%= ENV['INTRANET_SINOREDI_DATABASE_PASSWORD'] %>